<?php
$editar = Obj()->Session->getPermiso('AXIACT');

$data = Obj()->AccionController->findAccion();

$Form = Obj()->BuiltForm->init([
            "title"=>AXI_5,
            "alias"=>AXI,
            "ajaxSubmit"=>"Exe.AccionView.postEditAccion();",
            "attr"=>[
                "id"=>"formEditAccion",
                "name"=>"formEditAccion",
                "class"=>"modal fade"
            ],
            "noSubmit"=>$editar['permiso'] //cuando no tiene permiso de grabar, el enter en elementos no funciona
        ]);

$Form->addField([
    "label"=>[
        "label"=>AXI_6,
        "attr"=>["class"=>"label col col-2"]
    ],
    "field"=>[
        "attr"=>[
            "type"=>"text",
            "id"=>"txt_accion",
            "name"=>"txt_accion",
            "value"=>$data['descripcion']
        ],
        "help"=>AXI_10,
        "iconrequired"=>true,
        "validate"=>["required:true","minlength:3"]
    ]
]);

$Form->addField([
    "label"=>[
        "label"=>AXI_7,
        "attr"=>["class"=>"label col col-2"]
    ],
    "field"=>[
        "csswidth"=>"col col-3",
        "attr"=>[
            "type"=>"text",
            "id"=>"txt_alias",
            "name"=>"txt_alias",
            "value"=>$data['alias']
        ],
        "help"=>AXI_11,
        "iconrequired"=>true,
        "validate"=>["required:true","rangelength:[2,5]"]
    ]
]);

$Form->addField([
    "label"=>[
        "label"=>AXI_8,
        "attr"=>["class"=>"label col col-2"]
    ],
    "field"=>[
        "attr"=>[
            "type"=>"text",
            "id"=>"txt_icono",
            "name"=>"txt_icono",
            "value"=>$data['icono']
        ],
        "help"=>AXI_12,
        "iconrequired"=>true,
        "validate"=>["required:true","minlength:3"]
    ]
]);

$Form->addField([
    "label"=>[
        "label"=>AXI_9,
        "attr"=>["class"=>"label col col-2"]
    ],
    "field"=>[
        "attr"=>[
            "type"=>"text",
            "id"=>"txt_theme",
            "name"=>"txt_theme",
            "value"=>$data['theme']
        ],
        "help"=>AXI_13,
        "iconrequired"=>true,
        "validate"=>["required:true","minlength:3"]
    ]
]);

$Form->addField([
    "label"=>[
        "label"=>LBL_ACTIVO,
        "attr"=>["class"=>"label col col-2"]
    ],
    "field"=>[
        "csswidth"=>"col col-3",
        "attr"=>[
            "type"=>"checkbox",
            "id"=>"chk_activo",
            "name"=>"chk_activo",
            "value"=>"1",
            "checked"=>($data['estado'] == '1')?true:false
        ]
    ]
]);

if($editar['permiso']){
    $Form->addButton([
        "label"=>$editar['accion'],
        "icon"=>$editar['icono'],
        "attr"=>[
            "id"=>"btnSbAccion",
            "type"=>"submit",
            "class"=>$editar['theme']
        ]
    ]);
}

$Form->addButton([
    "label"=>LBL_CLOSE,
    "icon"=>ICON_CLOSE,
    "attr"=>[
        "type"=>"button",
        "class"=>THEME_CLOSE
    ]
]);

$Form->view(); 