<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 18-03-2015 23:03:01 
* Descripcion : indexEmpleados.phtml
* ---------------------------------------
*/
    
Vendor\Tools::widgetOpen(array(
        "id"=>AXI,
        "title"=>AXI_1
    )); 
?>


<!--<div id="<?php echo AXI; ?>gridAcciones2"></div>-->

<div id="<?php echo AXI; ?>gridAcciones"></div>

<?php 
    Vendor\Tools::widgetClose(); 
