<?php
/*
 * Documento   : formNewMenu
 * Creado      : 10-jul-2014
 * Autor       : ..... .....
 * Descripcion : 
 */
$grabar = Obj()->Session->getPermiso('MNUGR');

$Form = Obj()->BuiltForm->init([
                "title"=>MENU_1,
                "alias"=>MENU,
                "ajaxSubmit"=>"Exe.MenuView.postNewMenu();",
                "attr"=>[
                    "id"=>"formNewMenu",
                    "name"=>"formNewMenu",
                    "class"=>"modal fade"
                ],
                "noSubmit"=>$grabar['permiso'] //cuando no tiene permiso de grabar, el enter en elementos no funciona
            ]);

$Form->addField([
    "label"=>[
        "label"=>MENU_2,
        "attr"=>["class"=>"label col col-2"]
    ],
    "field"=>[
        "attr"=>[
            "type"=>"text",
            "id"=>"txt_menu",
            "name"=>"txt_menu"
        ],
        "help"=>MENU_7,
        "iconrequired"=>true,
        "validate"=>["required:true","minlength:3"]
    ]
]);

$Form->addField([
    "label"=>[
        "label"=>MENU_3,
        "attr"=>["class"=>"label col col-2"]
    ],
    "field"=>[
        "csswidth"=>"col col-8",
        "attr"=>[
            "type"=>"text",
            "id"=>"txt_titulo",
            "name"=>"txt_titulo"
        ],
        "help"=>MENU_8
    ]
]);

$Form->addField([
    "label"=>[
        "label"=>MENU_4,
        "attr"=>["class"=>"label col col-2"]
    ],
    "field"=>[
        "csswidth"=>"col col-6",
        "attr"=>[
            "type"=>"text",
            "id"=>"txt_icono",
            "name"=>"txt_icono"
        ],
        "help"=>MENU_9
    ]
]);

$Form->addField([
    "label"=>[
        "label"=>MENU_5,
        "attr"=>["class"=>"label col col-2"]
    ],
    "field"=>[
        "csswidth"=>"col col-6",
        "attr"=>[
            "type"=>"text",
            "id"=>"txt_alias",
            "name"=>"txt_alias"
        ],
        "help"=>MENU_10
    ]
]);

$Form->addField([
    "label"=>[
        "label"=>MENU_6,
        "attr"=>["class"=>"label col col-2"]
    ],
    "field"=>[
        "csswidth"=>"col col-8",
        "attr"=>[
            "type"=>"text",
            "id"=>"txt_ajax",
            "name"=>"txt_ajax"
        ],
        "help"=>MENU_11
    ]
]);



//$Form->addField([
//    "label"=>[
//        "label"=>MENU_6,
//        "attr"=>["class"=>"label col col-2"]
//    ],
//    "field"=>[
//        "csswidth"=>"col col-8",
//        "attr"=>[
//            "type"=>"textarea",
//            "id"=>"txt_ajax",
//            "name"=>"txt_ajax",
//            "class"=>"form-control"
//        ],
//        "help"=>MENU_11
//    ]
//]);


$Form->addField([
    "label"=>[
        "label"=>LBL_ACTIVO,
        "attr"=>["class"=>"label col col-2"]
    ],
    "field"=>[
        "csswidth"=>"col col-3",
        "attr"=>[
            "type"=>"checkbox",
            "id"=>"chk_activo",
            "name"=>"chk_activo",
            "value"=>"1",
            "checked"=>true
        ]
    ]
]);

if($grabar['permiso']){
    $Form->addButton([
        "label"=>$grabar['accion'],
        "icon"=>$grabar['icono'],
        "attr"=>[
            "id"=>"btnGrabaMnu",
            "type"=>"submit",
            "class"=>$grabar['theme']
        ]
    ]);
}

$Form->addButton([
    "label"=>LBL_CLOSE,
    "icon"=>ICON_CLOSE,
    "attr"=>[
        "type"=>"button",
        "class"=>THEME_CLOSE
    ]
]);

$Form->view(); 