<?php
/* 
* ---------------------------------------
* --------- CREATED BY GS ----------
* fecha:        24-10-2015 16:10:26 
* Descripcion : formEdit.phtml
* ---------------------------------------
*/ 

$editar = Obj()->Session->getPermiso("FASEACT");

$data = Obj()->FaseController->find();

$Form = Obj()->BuiltForm->init([
            "title"=>FASE_3,
            "alias"=>FASE,
            "ajaxSubmit"=>"Exe.FaseView.postEdit();",
            "attr"=>[
                "id"=>"formEdit",
                "name"=>"formEdit",
                "class"=>"modal fade"
            ],
            "noSubmit"=>$editar["permiso"] 
        ]);

$Form->addField([
    "label" => [
        "label" => LBL_DESCRIPCION,
        "attr" => ["class" => "label col col-2"]
    ],
    "field" => [
        "attr" => [
            "type" => "text",
            "id" => "txt_descripcion",
            "name" => "txt_descripcion",
            "value" => $data['descripcion']
        ],
        "help" => FASE_4,
        "iconrequired" => true,
        "validate" => ["required:true", "minlength:3"]
    ]
]);

$Form->addField([
    "label"=>[
        "label"=>LBL_ACTIVO,
        "attr"=>["class"=>"label col col-2"]
    ],
    "field"=>[
        "csswidth"=>"col col-3",
        "attr"=>[
            "type"=>"checkbox",
            "id"=>"chk_activo",
            "name"=>"chk_activo",
            "value"=>"1",
            "checked"=>($data["estado"] == "1")?true:false
        ]
    ]
]);

if($editar["permiso"]){
    $Form->addButton([
        "label"=>$editar["accion"],
        "icon"=>$editar["icono"],
        "attr"=>[
            "id"=>"btnEdit",
            "type"=>"submit",
            "class"=>$editar["theme"]
        ]
    ]);
}

$Form->addButton([
    "label"=>LBL_CLOSE,
    "icon"=>ICON_CLOSE,
    "attr"=>[
        "type"=>"button",
        "class"=>THEME_CLOSE
    ]
]);

$Form->view(); 
        